name: proxy

on:
    push:

jobs:
  no_proxy:
    runs-on: killercoda
    steps:
      - name: Verify Proxy Settings
        run: |
          echo "HTTPS Proxy: $https_proxy"
          echo "HTTP Proxy: $http_proxy"
          echo "No Proxy: $no_proxy"
          curl -v https://httpbin.org/ip
  check_proxy:
    runs-on: kk-k
    steps:
      - name: Verify Proxy Settings
        run: |
          echo "HTTPS Proxy: $https_proxy"
          echo "HTTP Proxy: $http_proxy"
          echo "No Proxy: $no_proxy"
          curl -v https://httpbin.org/ip